# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\">\n\x11GetServiceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\"?\n\x12GetServiceResponse\x12)\n\x07service\x18\x01 \x03(\x0b\x32\x18.service.ServiceResponse\":\n\x0fServiceResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x32Y\n\x11ServiceController\x12\x44\n\x07GetList\x12\x1a.service.GetServiceRequest\x1a\x1b.service.GetServiceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSERVICEREQUEST']._serialized_start=26
  _globals['_GETSERVICEREQUEST']._serialized_end=88
  _globals['_GETSERVICERESPONSE']._serialized_start=90
  _globals['_GETSERVICERESPONSE']._serialized_end=153
  _globals['_SERVICERESPONSE']._serialized_start=155
  _globals['_SERVICERESPONSE']._serialized_end=213
  _globals['_SERVICECONTROLLER']._serialized_start=215
  _globals['_SERVICECONTROLLER']._serialized_end=304
# @@protoc_insertion_point(module_scope)
