version: "3.2"
services:

  authentication:
    image: authentication:latest
    build: ./Authentication
    container_name: authentication

    ports:
        - 8000:8001
    volumes:
      - .:/code
    networks:
        - pod_net
    depends_on:
      - rabbitmq
  baseInfo:
    image: baseinfo
    build: ./BaseInfo
    container_name: baseInfo

    ports:
        - 8000:8002
    
    networks:
        - pod_net
    depends_on:
      - rabbitmq
  commerce:
    image: commerce:latest
    build: ./Services/Commerce
    container_name: commerce

    ports:
        - 8000:8003
    
    networks:
        - pod_net
    depends_on:
      - rabbitmq
  service:
    image: service:latest
    build: ./Services/Service
    container_name: service

    ports:
        - 8000:8004
    
    networks:
        - pod_net
    depends_on:
      - rabbitmq
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: configs/Dockerfile
    container_name: nginx

    ports:
        - 80:80
        - 443:443
    
    networks:
        - pod_net
    depends_on:
      - rabbitmq
    
  rabbitmq:
    image: rabbitmq:3.12.13-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - pod_net

networks:
  pod_net:
    driver: bridge