version: "3.2"
services:

  authentication:
    image: authentication:latest
    build: ./Authentication
    container_name: authentication
    command: > 
      sh -c "./rabbit.sh && python manage.py runserver  "

  

    networks:
        - pod_net
    depends_on:
      - rabbitmq
  baseInfo:
    image: baseinfo
    build: ./BaseInfo
    container_name: baseInfo
    command: > 
      sh -c "./rabbit.sh && python manage.py runserver  "

    
    networks:
        - pod_net
    depends_on:
      - rabbitmq
  commerce:
    image: commerce:latest
    build: ./Services/Commerce
    container_name: commerce
    command: > 
      sh -c "./rabbit.sh && python manage.py runserver  "
   
    
    networks:
        - pod_net
    depends_on:
      - rabbitmq
  service:
    image: service:latest
    build: ./Services/Service
    container_name: service
    command: > 
      sh -c "./rabbit.sh && python manage.py runserver  "

  
    
    networks:
        - pod_net
    depends_on:
      - rabbitmq
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: configs/Dockerfile
    container_name: nginx


    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro

    ports:
        - 80:80
        - 443:443
    
    networks:
        - pod_net
    depends_on:
      - rabbitmq
    
  rabbitmq:
    image: rabbitmq:3.12.13-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - pod_net

networks:
  pod_net:
    driver: bridge