# Generated by Django 5.0.2 on 2024-03-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaluser',
            name='Province',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='legaluser',
            name='address',
            field=models.IntegerField(),
        ),
    ]
