# Generated by Django 5.0.2 on 2024-03-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legaluser',
            name='buissnessType',
        ),
        migrations.RemoveField(
            model_name='legaluser',
            name='presenterLastname',
        ),
        migrations.RemoveField(
            model_name='legaluser',
            name='presenterName',
        ),
        migrations.RemoveField(
            model_name='legaluser',
            name='presenterPhone',
        ),
        migrations.AddField(
            model_name='legaluser',
            name='companyTitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='legaluser',
            name='postalCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='legaluser',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='legaluser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
