# Generated by Django 5.0.2 on 2024-03-08 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_legaluser_buissnesstype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legaluser',
            options={'verbose_name_plural': 'LegalUser'},
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, default=0, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_waller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
