# Generated by Django 5.0.2 on 2024-03-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_legaluser_province_alter_legaluser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaluser',
            name='Province',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='legaluser',
            name='address',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='legaluser',
            name='companyID',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
