# Generated by Django 5.0.2 on 2024-03-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_last_name_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaluser',
            name='companyTitle',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Province',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
