# Generated by Django 5.0.2 on 2024-03-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_legaluser_companytitle_alter_user_province_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realuser',
            options={'verbose_name_plural': 'RealUser'},
        ),
    ]
