# Generated by Django 4.2 on 2025-05-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_realuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
     
    ]
