# Generated by Django 4.2 on 2025-05-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_email_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Province',
            new_name='province',
        ),
      
    ]
