# Generated by Django 5.0.2 on 2025-10-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_province_user_province_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legaluser',
            old_name='companyID',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='legaluser',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='legaluser',
            old_name='companyTitle',
            new_name='company_title',
        ),
    ]
