# Generated by Django 5.0.2 on 2025-10-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_companyid_legaluser_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='postalCode',
            new_name='postal_code',
        ),
    ]
