# Generated by Django 5.0.2 on 2024-03-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.IntegerField(),
        ),
    ]
