# Generated by Django 5.0.2 on 2024-03-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_city_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceBrands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CommerceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBrands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=15)),
            ],
        ),
    ]
