# Generated by Django 4.2 on 2024-06-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_commercebrands_commercecategory_servicebrands_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commercebrands',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commercecategory',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='province',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicebrands',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
