# Generated by Django 5.0.2 on 2024-03-07 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('user_id', models.IntegerField()),
                ('day_price', models.IntegerField()),
                ('month_price', models.IntegerField()),
                ('code', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('logistic_price', models.IntegerField()),
                ('free_transport', models.BooleanField()),
                ('discount', models.IntegerField()),
                ('category', models.IntegerField()),
                ('brand', models.IntegerField()),
                ('available_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service/images')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceVotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('votes', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
    ]
