# Generated by Django 4.2 on 2024-03-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service_created_at_service_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimages',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
