# Generated by Django 4.2 on 2025-04-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicecomments_reply_servicecomments_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicequestions',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicevotes',
            name='votes',
            field=models.FloatField(),
        ),
    ]
