# Generated by Django 4.2 on 2025-05-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_servicequestions_title_alter_servicevotes_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
