# Generated by Django 5.0.2 on 2025-09-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='dimensions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
