# Generated by Django 4.2 on 2024-03-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_serviceimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimages',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
