# Generated by Django 5.0.2 on 2024-03-07 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('user_id', models.IntegerField()),
                ('day_price', models.IntegerField()),
                ('month_price', models.IntegerField()),
                ('code', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('logistic_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('category', models.IntegerField()),
                ('brand', models.IntegerField()),
                ('available_count', models.IntegerField()),
                ('free_transport', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CommerceComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=200)),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commerce')),
            ],
        ),
        migrations.CreateModel(
            name='CommerceImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='commerce/images')),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commerce')),
            ],
        ),
        migrations.CreateModel(
            name='CommerceVotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('votes', models.IntegerField()),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commerce')),
            ],
        ),
    ]
