# Generated by Django 4.2 on 2025-04-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('lentgh', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('logistic_price', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('brand', models.IntegerField(blank=True, null=True)),
                ('available_count', models.IntegerField(blank=True, null=True)),
                ('free_transport', models.BooleanField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('fair_price', models.BooleanField(blank=True, default=True, null=True)),
                ('valid_seller', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommerceVotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('votes', models.IntegerField()),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commerce')),
            ],
        ),
        migrations.CreateModel(
            name='CommerceImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commerce')),
            ],
        ),
        migrations.CreateModel(
            name='CommerceComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commerce')),
            ],
        ),
    ]
