# Generated by Django 5.0.2 on 2025-10-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerce',
            name='country',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
