# Generated by Django 4.2 on 2025-04-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercecomments',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CommerceNegotiate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commerce')),
            ],
        ),
    ]
