# Generated by Django 4.2 on 2024-03-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commerce_created_at_commerce_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerce',
            name='available_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='brand',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='day_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='free_transport',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='logistic_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='month_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
