# Generated by Django 4.2 on 2025-04-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commercecomments_user_id_commercenegotiate'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercecomments',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.commercecomments'),
        ),
        migrations.CreateModel(
            name='CommerceQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commerce')),
            ],
        ),
    ]
