# Generated by Django 4.2 on 2024-03-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_commerce_available_count_alter_commerce_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerceimages',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
