# Generated by Django 4.2 on 2025-04-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_commercecomments_reply_commercequestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercevotes',
            name='votes',
            field=models.FloatField(),
        ),
    ]
