# Generated by Django 4.2 on 2024-03-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_commerceimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerceimages',
            name='image',
            field=models.ImageField(upload_to='commerce/images'),
        ),
    ]
