# Generated by Django 4.2 on 2025-05-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_commerce_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commerce',
            old_name='lentgh',
            new_name='length',
        ),
    ]
