# Generated by Django 5.0.2 on 2025-09-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_lentgh_commerce_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commerce',
            old_name='height',
            new_name='dimensions',
        ),
        migrations.RemoveField(
            model_name='commerce',
            name='length',
        ),
        migrations.RemoveField(
            model_name='commerce',
            name='width',
        ),
        migrations.AlterField(
            model_name='commerce',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
