http {
    upstream authentication {
        server authentication:8000;
    }

    upstream baseInfo {
        server baseInfo:8000;
    }
      upstream service {
        server service:8000;
    }
      upstream commerce {
        server commerce:8000;
    }
    upstream log{
        server log:8000;
    }
     upstream content{
        server content:8000;
    }
   
    upstream order {
        server order:8000;
    }
    upstream search{
        server search:8000;
    }
   
       upstream front {
        server front:3000;
    }
       upstream admin {
        server admin:3000;
    }
   
   

    server {
        listen 80;
        server_name api.pod-app.com localhost;
        proxy_set_header Host $host;

        location /auth/ {
            proxy_pass http://authentication;
        }

        location /baseInfo/ {
            proxy_pass http://baseInfo;
        }
                location /commerce/ {
            proxy_pass http://commerce;
        }
                location /service/ {
            proxy_pass http://service;
        }
                location /log/ {
            proxy_pass http://log;
        }
               location /order/ {
            proxy_pass http://order;
        }
              location /content/ {
            proxy_pass http://content;
        }
        location /search/ {
            proxy_pass http://search;

        }
         
    
    
    }
     server {
        listen 80;
        server_name pod-app.com;
        
        location / {
            proxy_pass http://front;
        }
     }
      server {
        listen 80;
        server_name admin.pod-app.com;
        
        location / {
            proxy_pass http://admin;
        }    
    }
}

events {}