server {
    listen 80;
    server_name pod.ir;

    location /auth {
        proxy_pass http://localhost:8001;
    }

    location /baseInfo {
        proxy_pass http://localhost:8002;
    }

    location /commerce {
        proxy_pass http://localhost:8003;
    }
      location /service {
        proxy_pass http://localhost:8004;
    }


    # Add more location blocks for additional paths and ports

    # Default location block
    location / {
        return 404;
    }
}