http {
    upstream authentication {
        server authentication:8000;
    }

    upstream baseInfo {
        server baseInfo:8000;
    }
      upstream service {
        server service:8000;
    }
      upstream commerce {
        server commerce:8000;
    }
     upstream front {
        server front:3000;
    }

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://authentication;
        }

        location /baseInfo/ {
            proxy_pass http://baseInfo;
        }
                location /commerce/ {
            proxy_pass http://commerce;
        }
                location /service/ {
            proxy_pass http://service;
        }
               location / {
            proxy_pass http://front;
        }
    }
}

events {}