# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: commerce.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'commerce.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ommerce.proto\x12\x08\x63ommerce\"?\n\x12GetCommerceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\"C\n\x13GetCommerceResponse\x12,\n\x08\x63ommerce\x18\x01 \x03(\x0b\x32\x1a.commerce.CommerceResponse\";\n\x10\x43ommerceResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x32^\n\x12\x43ommerceController\x12H\n\x07GetList\x12\x1c.commerce.GetCommerceRequest\x1a\x1d.commerce.GetCommerceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commerce_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCOMMERCEREQUEST']._serialized_start=28
  _globals['_GETCOMMERCEREQUEST']._serialized_end=91
  _globals['_GETCOMMERCERESPONSE']._serialized_start=93
  _globals['_GETCOMMERCERESPONSE']._serialized_end=160
  _globals['_COMMERCERESPONSE']._serialized_start=162
  _globals['_COMMERCERESPONSE']._serialized_end=221
  _globals['_COMMERCECONTROLLER']._serialized_start=223
  _globals['_COMMERCECONTROLLER']._serialized_end=317
# @@protoc_insertion_point(module_scope)
