# Generated by Django 4.2 on 2025-04-16 07:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='news',
            name='resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
